### ISSUE TITLE
exe don't work

### ISSUE THREAD

**Issue by guzur** [htacg/tidy-html5#311]
I'm trying to compile tidy library on Windows with MinGW . 

When I try to compile with Eclipse and Cmake I have an error with this line: 
if ( !GetFileSizeEx( fp, (LARGE_INTEGER*)&fin->size ) 
In mappedio.c line 207. GetFileSizeEx is unknown.

If I comment this code, I can compile without errors the library, but when I try to execute the exe it gets locked or freeze. There isn't any output.

Anyone can help me with this?
Thank you very much.

**Comment by geoffmcl** [comment]
@guzur glad to hear of someone trying MinGW build in Windows... please to meet you and I will try to help where I can... In fact I would try to install MinGW in my Windows 7 64-bit, and would hope that I can generate 32 and 64 bit binaries from it.

But first please help me with a few things -

A: What is the correct C/C++ define for MinGW? I have seen `#if defined( __MINGW32__ )` in other sources. Is this correct?

If it is then the line ver 195 iine in mappedio.c `#if defined(_MSC_VER) && (_MSC_VER < 1300)` could be changed to `#if (defined(_MSC_VER) && (_MSC_VER < 1300)) || (defined(__MINGW32__))` to use the standard `GetFileSize()`...

Or there could be other fixes for this, like using stat/stat64...

BUT it is really important to get the exact correct file size into the MappedFileSource::size, a LONGLONG 64-bit variable. And if this does not get set then that may be the cause of your binary hang, but do not know...

B: Getting the correct install of MinGW. I found this [download](https://sourceforge.net/projects/mingw/files/) site, but as usual there are choices. Like what is MSYS?

But I assume I can start with `mingw-get-setup.exe (86.5 kB)` and see what that gives me. 

What have you installed? In what OS? 64 or 32 bit?

C: Cmake and Eclipse

I did not understand your "I try to compile with Eclipse or Cmake"? What do you mean by `or` here? As I see it that they work together, not or. CMake generates the Eclipse make files first, then I use Eclipse to do the compile and link...

My cmake --help offers me a generator "Eclipse CDT4 - MinGW Makefiles". So I assume the first step is to generate these. Is that what you did?

I have a (`partial` or `faulty` I think) install of MinGW with `Emscripten`, and when I tried in `build\cmake` to use `cmake ..\.. -G "Eclipse CDT4 - MinGW Makefiles"` it FAILS.

The first thing is it could not determine the Eclipse version. I found [downloads](https://eclipse.org/downloads/) and assume I can just download the installer? 

What did you use to install Eclipse?

Next the cmake test compile with gcc (D:\Emscripten\mingw\4.6.2_32bit\gcc.exe) failed to compile. 

But I would probably unistall all that `Emscripten` stuff, and as mentioned above would intall MinGW fresh.

Sorry for the twenty questions!

But it seems the only way I can help is to first have the ability to do a mingw compile myself. I will try to do that... But that may take some time. I will be away from my computers from the 23rd until the end of November, so it may be after that...

However, meantime maybe there are other MinGW users out there that can help...

We would certainly like to add a Windows MinGW compiled of tidy to our binary distributions.

**Comment by guzur** [comment]
Thank you very much geoffmcl for your answer. 
I'm not now in my computer so I can't answer some questions.

C: Cmake and Eclipse

"I try to compile with Eclipse or Cmake" => "I try to compile with Eclipse and Cmake" 
I want to type "and" not "or". I already edited.

Tomorrow, I will try to answer as much as I can.

**Comment by guzur** [comment]
**A:**
I try compile with this line #if (defined(_MSC_VER) && (_MSC_VER < 1300)) || (defined(__MINGW32__)) but it didn't work. The error output is this one.
``
C:\tidy\src\mappedio.c: In function 'initMappedFileSource':``
``C:\tidy\src\mappedio.c:199:29: error: lvalue required as left operand of assignm
ent``
``         (DWORD)pli->LowPart = GetFileSize( fp, (DWORD *)&pli->HighPart );``
``CMakeFiles\tidy-static.dir\build.make:637: recipe for target 'CMakeFiles/tidy-st
atic.dir/src/mappedio.c.obj' failed``
``mingw32-make.exe[2]: *** [CMakeFiles/tidy-static.dir/src/mappedio.c.obj] Error 1
``

**B:**
Yes that's what I installed in a Windows 7 64-bits.

**C: Cmake and Eclipse**

"I try to compile with Eclipse or Cmake" => "I try to compile with Eclipse and Cmake" 
I want to type "and" not "or". I already edited.

This is what I used to compile with MinGW:
1. cd build/cmake
2. cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=c:/tidy
3. cmake --build . --config Release

And for eclipse I compiled with the IDE.


Thank you very much for your help.

**A final question** this tidy library it's only for windows or unix SO? I came from trying to use gumbo but gumbo library don't work with xhtml only html5 so I was trying to use tidy. I want to export it after make it work to iOS and android. Any problem with this?

**Comment by geoffmcl** [comment]
@guzur thanks for the information... you seemed to have posted twice... can you remove one...

**A: Compile Error**

Ok, it looks like MinGW also does not support the union members `LowPart` and `HighPart` of the  `LARGE_INTEGER` structure... sad, but not a problem.

For MinGW it seems we need another way to get the file size from a file handle... put the file size into the 64-bit LONGLONG size member? Maybe -

```
#if defined(__MINGW32__)
    {
        DWORD lowVal, highVal;
        lowVal = GetFileSize(fp, &highVal);
        if ((lowVal == INVALID_FILE_SIZE) && (GetLastError() != NO_ERROR))
        {
            TidyFree(allocator, fin);
            return -1;
        }
        fin->size = highVal;
        fin->size = (fin->size << 32);
        fin->size += lowVal;
    }
#else /* NOT a MinGW build */
#if defined(_MSC_VER) && (_MSC_VER < 1300)  /* less than msvc++ 7.0 */
    // all the current stuff
    
#endif /* MinGW y/n */
```

In my quick testing the above sample code worked fine... unfortunately I do not have any 4 GB plus html files to really test the highVal...

Otherwise we would need to go deeper, and pass in either the file name and use stat/stat64 to get the size, or in fact do such a stat earlier and pass in the LONGLONG size to this function...

So there are other alternatives...

**B: MinGW install**

As stated I removed all previous and did a fresh MinGW install to D:\MinGW... I found it does NOT add D:\MinGW\bin to the PATH, which I am glad for, because there are a LOT of things in that folder that I would NOT want in my normal PATH...

But I added that just before doing the cmake config and generation... But it warned me that Eclipse did not support the build in a subdirecotry of the source... 

So my tidy is in F:\Projects\tidy-html5, and I was in build\cmake, so I created a sibling directory F:\Projects\build-tidy-mingw, and it seemed the cmake config/gen went fine... I got .cproject and .project files built...

BUT still to install Eclipse to try the next step... 

And also note this seems a 32-bit install of MinGW, but found a mingw-w64-install.exe which I also want to try...

Still some step to go...

**C: CMake and Eclipse**

Assume some typos in what you used, in that you missed the `..\..` directory, but that looks fine otherwise...

But also wonder why you do not add the IDE in the generator string, like `-G "Eclipse CDT4 - MinGW Makefiles"`. It seems this causes the `CMAKE_ECLIPSE_VERSION` to be set, but maybe is not important...

**D: iOS and android**

I do not know `gumbo`, but I would see no immediate problem with tidy iOS and android compiles. Maybe some functions would need to be substituted, but tidy has no special other 3rdparty library dependencies, and quite normal file and IO functions from the OS...

Good luck with that.

**Comment by guzur** [comment]
I downloaded a compiled exe for windows from here: 
http://www.paehl.com/open_source/?HTML_Tidy_for_Windows
and didnt work. So maybe something about Windows? I tried in other computers and the same happends.

**Comment by geoffmcl** [comment]
@guzur yes, that [HTML_Tidy_for_Windows](http://www.paehl.com/open_source/?HTML_Tidy_for_Windows) is an **OLD** 2009 version of tidy, but downloading the tidy.zip, and unzipping, it ran fine for me.

And note he does have a more recent [HTML_Tidy_for_HTML5](http://www.paehl.com/open_source/?HTML_Tidy_for_HTML5) with version 5.1.20 which is quite recent - 2015.11.05. Both the 32-bit and 64-bit tidy.exe ran ok in my system, at least with the -v option.

So not quite sure what you mean by **didnt work**? You do know that running tidy with no input file puts it in reading stdin mode, and the only exit from that is ctrl+c?

We also have recent versions in a zip - see http://binaries.html-tidy.org/

I must get around to publishing later versions, and as mentioned would love to add a MinGW build. 

We have been considering expanding the naming convention to say `tidy-$VERSION-$CPU-$BITNESS.zip` - see #258 and #295, and maybe should even consider `tidy-$VERSION-$CPU-$BITNESS-$COMPILER.zip`, then we could have `MSVC10`, `MinGW<v>`, etc... but need feedback and specific platform support to do all this...

**Comment by guzur** [comment]
Hi geoffmcl thank you for your time. 
I executed that binarys with this line:
``tidy index.html > output.html``
Is it right?
The output.html file was created but is empty and the exe keeps running 5 minutes later so... Something is wrong isn't it?

**Comment by geoffmcl** [comment]
@guzur well the first thing is while redirecting the ouput is possible, the best way is to specify an output file, before the input, like `tidy -o output.htm index.html`.

But what do you get with `tidy -v`? Does this just show the version? And `echo %ERRORLEVEL%` shows `0`?

**Comment by guzur** [comment]
@geoffmcl  the ``tidy -v`` didn't print anything the ``echo %ERRORLEVEL%`` shows ``0``

**Comment by geoffmcl** [comment]
@guzur ok, maybe it is time to run it in a Debugger!

Reading around it seems MinGW ships with a port of the unix gdb - see [here](http://stackoverflow.com/questions/4671900/how-do-i-use-the-mingw-gdb-debugger-to-debug-a-c-program-in-windows), and it seems Eclipse can connect to that in the [IDE](http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Ftasks%2Fcdt_t_debug_prog.htm)...

To enable debug symbols to be added to the binary, you will probably need to build the debug version, `-DCMAKE_BUILD_TYPE=Debug`. As you can see in the first link above this adds a `-g` option the the compile. You might also add `-DCMAKE_VERBOSE_MAKEFILE=ON` just to check the `-g` gets added...

You could also create a simple `Hello World` program, and see what that does, like -

```
#include <stdio.h>
int main (int argc, char **argv)
{
    printf("Hello World\n");
    return 1;
}
```

Compile it like in the first link, run it, and run it in the gdb debug... 

After loading the exe set a breakpoint at main, like `break main`, and then `run` should stop at `main`, and print the first line. A `step` command should advance to the next statement... but I have **not** used gdb very often, so you have to read up on [gdb](https://sourceware.org/gdb/current/onlinedocs/gdb/)...

Just out of interest, can you post your tidy.exe somewhere I can download it from?

Really, I have no idea why your Eclipse/MinGW built tidy fails! But running in the gdb debugger you may be able to provide more clues... tidy.exe certainly does not seem to be built correctly...

**Comment by geoffmcl** [comment]
@guzur have successfully built tidy using MinGW-32, and it all works fine for me.

Had to apply the following two patches -

```
diff --git a/include/tidyplatform.h b/include/tidyplatform.h
index a40e0a0..ea999c5 100644
--- a/include/tidyplatform.h
+++ b/include/tidyplatform.h
@@ -469,7 +469,7 @@ extern "C" {
 */
 #if defined(_WIN32) && !defined(__MSL__) && !defined(__BORLANDC__)
 
-#ifndef __WATCOMC__
+#if !(defined(__WATCOMC__) || defined(__MINGW32__))
 #define fileno _fileno
 #define setmode _setmode
 #endif
diff --git a/src/mappedio.c b/src/mappedio.c
index 61cf748..f80c978 100644
--- a/src/mappedio.c
+++ b/src/mappedio.c
@@ -191,7 +191,21 @@ static int initMappedFileSource( TidyAllocator *allocator, TidyInputSource* inp,
     fin = (MappedFileSource*) TidyAlloc( allocator, sizeof(MappedFileSource) );
     if ( !fin )
         return -1;
-    
+
+#if defined(__MINGW32__)
+    {
+        DWORD lowVal, highVal;
+        lowVal = GetFileSize(fp, &highVal);
+        if ((lowVal == INVALID_FILE_SIZE) && (GetLastError() != NO_ERROR))
+        {
+            TidyFree(allocator, fin);
+            return -1;
+        }
+        fin->size = highVal;
+        fin->size = (fin->size << 32);
+        fin->size += lowVal;
+    }
+#else /* NOT a MinGW build */
 #if defined(_MSC_VER) && (_MSC_VER < 1300)  /* less than msvc++ 7.0 */
     {
         LARGE_INTEGER* pli = (LARGE_INTEGER *)&fin->size;
@@ -210,6 +224,7 @@ static int initMappedFileSource( TidyAllocator *allocator, TidyInputSource* inp,
         return -1;
     }
 #endif
+#endif /* MinGW y/n */
 
     fin->map = CreateFileMapping( fp, NULL, PAGE_READONLY, 0, 0, NULL );
```

The first was to remove a warning. The second was to provide a MinGW work-around for no `GetFileSizeEx()`, and no `LARGE_INTEGER` support in MinGW.

I have NOT yet installed Eclipse, so this was using the `MinGW32-make.exe` that comes with MinGW, so the commands were -

```
set PATH=D:\MinGW\bin;%PATH% # this is optional, only if MinGW\bin not already in the PATH
cmake ..\.. -G "MinGW Makefiles" # note, this is without Eclipse
mingw32-make # build using the Makefile generated
```

Then I could run the MinGW built `tidy.exe` without problems, and I also used it to run all the 228 tests without problems... Temporarily have add `MinGW` to the version, but need to think this through further...

```
tidy -v
HTML Tidy for Windows version 5.1.27.MinGW
```

This patch I have presently pushed to the `mingw-build` branch, so to test it do -

```
cd tidy-html5 # or wherever you have the git source
git pull    # make sure up to date
git checkout mingw-build # switch branches
git pull    # make sure up-to-date
```

Now that I can directly build using my 32-bit MinGW I will probably not pursue the Eclipse build, but it should not be a problem, using the correct generator. And will still try to find the time to install and test the MinGW 64-bit build... will take some time...

If you could get a chance to pull this **branch**, compile and test it, and if successful, close this issue, and I will get around to pulling it into `master`... thanks...

**Comment by guzur** [comment]
@geoffmcl Thank you for your work, I will try it as soon as possible and I will tell you the result.

Thank you.

**Comment by guzur** [comment]
@geoffmcl I compiled with your branch "minGW-build" and the result is the same the exe didn't work. I uploaded to dropbox and here you have a link to download it.

https://www.dropbox.com/s/nvc5zn5cohxbdq9/tidy.exe?dl=0

Is necessary something external?

**Comment by geoffmcl** [comment]
@guzur **wow**, I do not know what is wrong with your system???? I downloaded the tidy.exe you posted and it ran fine for me!!!

```
...\Downloads> .\tidy.exe -v
HTML Tidy for Windows version 5.1.27.MinGW
```

And it successfully **tidies** any HTML I feed it! It seems to work fine here...

And I have checked the EXE with some utilities like `dumpbin` in the MSVC command prompt, and it looks like a fine, normal windows PE executable... I do note the MinGW linker does NOT correctly set the timestamp - 50000 time date stamp Sun Jan 04 20:01:20 1970, but that is minor... It is a regular 32-bit app - 14C machine (x86), 10B magic # (PE32), etc, etc... 

I guess we should have seen this coming. I seem to remember you saying you downloaded the Win32/64 zip from `http://binaries.html-tidy.org/`, or from somewhere?, and they also **did not work**! Is that correct? If not please download one or more of the windows zips, unzip, and run `.\tidy.exe -v`...

Note I use a path name to the exe, `.\`, and add the `.exe` extension. This is to make sure you are running only that **exe**, and there is not another `tidy.exe, tidy.com, tidy.cmd, tidy.bat, etc` in your system PATH that gets run instead of the `tidy.exe` you built.

At present this does not feel like a MinGW problem at all, but something about your system... hope you find what...

**Comment by guzur** [comment]
Hi @geoffmcl !! I found the problem it was avast the Antivirus, I disconnected and it works!!! 
Thank you so much for all your work and fantastic staff. 

Cheers.

**Comment by geoffmcl** [comment]
@guzur wow, as simple as that!!!

Certainly not sure why an antivirus program would pick up on tidy! It only does file IO, no web hooks, etc??? Would never have expected this...

Assume we can close this... but feel free to re-open, or post a new issue... cheers...

**Comment by geoffmcl** [comment]
Have merged and deleted branch "minGW-build", and bumped version to 5.1.29, removing the `MinGW` rc from version... Have still to install the MinGW64 to ensure no compile problem with it... but the tidy32.exe is fine so hope 64-bit is also no problem.
